language: python
deploy:
  provider: pypi
  user: __token__
  password:
    secure: FliWy+w5ZKk0bjgX1Yp55LVvr+2opzmKV+iJmHfoO8uIilZQmcVyeyRFjumOfSB0cbkcifx0u+XaM1j2x3ZNNKiFKOgNsCM79Y52xSUgO5bRmuxs3Q2MTW3GVVpFKQPpebWdJ2CB4gj6P+XLjiVBcBIeF9aBU5ZUUpW7YfpnCYcGD/wzYMrXA5lF9L+g4+wWRsCTsc4SOvo4VSXKuYF/yJjdCGjmN4Btr4+j6xNnI1abGiDVQAcyn79wRNLdWEEYoU4qqWIdYefyf8jRuiMdcbmvckDkmB9xGAd8FgYRk65XRTTUQOeRTcyDptOLcVbTIAS3XzLthHijft07Lk68vYTXgAqbO0fMnDdvxxhJx1zfC3eMt6JPb+ykIRr/3hLAcVmMk1JtJx4wx477wnavzbY6ZMSDRgL/Or2L6sPKe/iRx3ywn9RAiFjPRCbqC9rsCFGAdFYwRMID6SQP8JCPbfkzzAblSacNh5ztpw3AXOQxwhD9wvjADszK/Hh21c2WrYg7GGKfAfhDixbRkIjoB7x9uV0sfEjwMMH9gBBc2qg1G2UCJwzaKTmW8Pq4wKAEE9+gL5Y4E6l/U4S2FsEJK4K2msaBfru4wBFhq1tbDiO4lCkJ6hus+ACM7ncX4WJCTecseCHwrXnC+6v0MvXBd6TwUxdx42/OuSSWqxJRxaI=
install:
script: