name: trainer_env
dependencies:
  - python=3.8
  - anaconda
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - cudatoolkit=10.2
  - conda-forge::python-graphviz
  - pip:
    - opencv-python
    - PySimpleGui
    - pydicom
    - psycopg2-binary
    - PySimpleGUI
    - flexx
    - gym # Might be superfluous, only used for reinforcement learning